version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
      args:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-'password'}
        - POSTGRES_USER=${POSTGRES_USER:-'postgres'}
        - POSTGRES_DB=${POSTGRES_DB:-'postgres'}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-'password'}
      - POSTGRES_USER=${POSTGRES_USER:-'postgres'}
      - POSTGRES_DB=${POSTGRES_DB:-'postgres'}
    ports:
      - "5432:5432"
    