version: '3.8'

services:
  adminer:
    build: 
      context: .
      dockerfile: Dockerfile.adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    volumes:
      - ./app:/app
    command: composer install
    working_dir: /app
    depends_on:
      - postgres


  symfony:
    build:
      context: .
      dockerfile: Dockerfile.symfony
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
