version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    ports:
      - "5432:5432"